name: numeral_systems
description: Easy converter to translate numeral systems

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  units_converter: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
